### ISSUE TITLE
Does not compile with threaded perls

### ISSUE THREAD

**Issue by eserte** [alexbyk/perl-evo-xs#1]
See http://matrix.cpantesters.org/?dist=Evo-XS%200.005;os=linux;reports=1#sl=0,1 for an overview --- almost all UNKNOWN reports (this mostly indicates compilation failures) are for threaded perls.

**Comment by alexbyk** [comment]
Thanks. I've rewritten this module from the scratch and now it should support MULTIPLICITY and THREADS
